herodevs_vue.settings:
  type: config_object
  label: 'HeroDevs Vue settings'
  mapping:
    herodevs_vue:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'HeroDevs Vue page title:'
        source_text:
          type: text
          label: 'CDN link for Vue'
block.settings.herodevs_vue_block:
  type: block_settings
  label: 'HeroDevs Vue block'
  mapping:
    herodevs_vue_block_settings:
      type: text
      label: 'HeroDevs Vue block settings'
